name: Test PKGBUILD

on:
  workflow_dispatch:
  push:
    paths:
      - 'pkg/arch/**'

jobs:
  test-pkgbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./pkg/arch/test.sh
